### ISSUE TITLE
Programmatically restoring?

### ISSUE THREAD

**Issue by whasf** [alphaleonis/AlphaVSS#14]
Your API looks great but I don't see any way to do a restore of a folder/file?

**Comment by whasf** [comment]
Is this project dead?

**Comment by alphaleonis** [comment]
I can only refer to the official documentation for the Volume Shadow Copy Service when it comes to the functionality of it.  If you see any particular method documented there that is not available in AlphaVSS, then let me know and I'll have a look at it.

Project is not dead, but not very active since not a lot happens in the underlying API:s.

**Comment by aflansburg** [comment]
Restores are probably out of the scope of VSS in general. Windows Server Backup (also VSC based) has a restore function, but involves restoring from the VHD using the metadata created during the backup process.

**Comment by whasf** [comment]
Thanks!
