### ISSUE TITLE
Why does VSS Croak Sometimes?

### ISSUE THREAD

**Issue by jzabroski** [alphaleonis/AlphaVSS#32]
Hi @alphaleonis ,

First off, your library has huge usage by us, indirectly, and its through these indirect usages I became aware of your great project -- you should feel very proud that multi-million dollar corporations are being powered by your software:

1. We use MSP360's Cloudberry Online Backup to backup _everything_ to the cloud (see screenshot below).
2. We use Red Gate SQL Clone to create clones of our production database server backup restores.  (We don't run AlphaVSS directly against the production mdf/ldf files, but restores of those files on development machines.)  The Agent in the Server/Client/Agent model uses AlphaVSS.

**My question to you is if you've seen the following problems**

#### Problem 1
... sometimes these tools have problems with Volume Shadow Service.  In particular, we notice sometimes that the volume stops showing up in `vssadmin list volumes` command, but the underlying VHD doesnt get deleted, AND when we try to delete it manually, it says that it's opened by the System process.  This error message to me suggests it's not SQL Clone Agent or your library at fault, but rather Volume Shadow Service has a bug in it where it deletes the header row but doesn't process the underlying storage deletion.

#### Problem 2
VSS dislikes Microsoft Distributed File System Replication, and only works if you configure it for one-way replication (with read-only replicas, not multi-master replicas).

![image](https://user-images.githubusercontent.com/447485/71278016-6ea01080-2324-11ea-9e07-749a96ca8b42.png)

![image](https://user-images.githubusercontent.com/447485/71277998-62b44e80-2324-11ea-89d1-f93618dcf5cd.png)

**Comment by alphaleonis** [comment]
Thank you for the encouraging words. :)  Even though AlphaVSS is not much more than a (perhaps not so) simple interop layer over the official VSS API.

I really wish I had some insights to share with you on your issues, but unfortunately while I've written AlphaVSS, I've actually not used it too much. (I guess writing the library took too much time for me to actually have time left to use it for the project I initially intended). 

In particular I have not seen the first issue you described, nor do I personally have any experience with DFS replication unfortunately.  But it sounds to me, just as you suspect, that there are some quirks with the underlying VSS rather than AlphaVSS (which as I said doesn't do much more than delegate calls to VSS).

I hope someone else in the community may have some more experience and insight they can share with you here.
